# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_auto_20171010_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='recommender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommend_membership_set', to='model.Idol'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='idol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_set', to='model.Idol'),
        ),
    ]
